### ISSUE TITLE
R install should enable shared libraries

### ISSUE THREAD

**Issue by wasade** [qiime/qiime-deploy-conf#107]
I'm not aware of a reason to avoid this, and it reduces deployment burden for others as R is a common package for a lot of other platforms. This was discussed on the forum [here](https://groups.google.com/forum/#!topic/qiime-forum/SfNbigF48JQ), but I disagree that enabling shared libraries as a compilation mod is a concern for QIIME (if it is, then that is a concern for R in general...)

**Comment by jairideout** [comment]
Closing since we stopped supporting R in qiime-deploy.
