### ISSUE TITLE
add PATH=$SGE_ROOT/bin/linux-x64:$PATH to env for ipython

### ISSUE THREAD

**Issue by antgonza** [qiime/qiime-deploy-conf#57]
While doing the EC2 AMI release for 1.7.0 we realized that we need to add PATH=$SGE_ROOT/bin/linux-x64:$PATH to the env for ipython notebook to work. This should be part of the deploy.

**Comment by jairideout** [comment]
@gregcaporaso and I tested the 1.9.0rc1 AMI we created and didn't have to set this (likely due to a way newer version of IPython and the fact that we're using `pip` to install it now). I think this is safe to close.
